name: Build & Push with Bake

on:
  push:
    branches: [ "main" ]

jobs:
  bake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/bake-action@v4
        with:
          files: docker-compose.yml
          push: true
          targets: apache
          set: |
            *.tags=devho/franken-php:latest
            *.tags=devho/franken-php:${{ github.sha }}