services:
  apache:
    build:
      context: .
      dockerfile: ./docker/frankenphp/Dockerfile
    ports:
      - target: 80
        published: 80
        protocol: tcp
    environment:
      SERVER_NAME: :80
    volumes:
      - ./:/app/public
      - caddy_data:/data
      - caddy_config:/config

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-quynh121201}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
  hasura:
    image: hasura/graphql-engine:v2.42.0
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    depends_on:
      database:
        condition: service_healthy
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-quynh121201}@database:5432/${POSTGRES_DB:-app}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET:-mysecretkey}
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management
    ports:
      - target: 5672
        published: 5672
        protocol: tcp
      - target: 15672
        published: 15672
        protocol: tcp
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-quynh}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-quynh121201}
      # RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: true

volumes:
    caddy_data:
    caddy_config:
    database_data:
