apiVersion: batch/v1
kind: Job
metadata:
  name: doctrine-migrations
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migration
        image: devho/franken-php:1741fbfda0b54a9e57d1f991fa20d7d3f325a4a9
        imagePullPolicy: Always
        workingDir: /app/public
        command: ["php", "bin/console", "doctrine:migrations:migrate", "--no-interaction"]
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: frankenphp
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: frankenphp
                key: DB_PORT
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: frankenphp
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: frankenphp-secret
                key: password
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: frankenphp-secret
                key: database_url
        envFrom:
          - configMapRef:
              name: frankenphp
