apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1 # Database thường chạy 1 bản để tránh xung đột dữ liệu (trừ khi dùng Cluster chuyên dụng)
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: frankenphp-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: frankenphp
                  key: DB
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data # Thư mục mặc định Postgres lưu data
          # Kiểm tra Postgres đã sẵn sàng nhận kết nối chưa
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "$(POSTGRES_DB)"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          # Nếu Postgres treo, Kubernetes sẽ restart container
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "$(POSTGRES_DB)"]
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc # Phải trùng tên với PVC ở Bước 1