apiVersion: v1
kind: Secret
metadata:
  name: frankenphp-secret
type: Opaque
stringData:
  password: mysecretpassword
  database_url: "postgresql://postgres:mysecretpassword@postgres-service:5432/myapp_db?serverVersion=15&charset=utf8"
