apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: frankenphp-image-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: frankenphp
      useAnnotations: true
